### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [alinawww/Jamming#3]
Met expectations.

I wish I could experiment, I really wanted to play with your use of FSCs here.  It is neat that you went to that level and in the long run it is a great practice to follow.

I don't think the other advisors have been doing this but I have been experimenting with learners and it has been great experience for me.

Good luck with your feature request if you plan to implement it.

**Comment by alinawww** [comment]
Thank you for the review  :) I am currently working on a react project at work and I really wanted to take this course to get a good base as at work I learned a couple of things on the fly. The FSCs are part of it. Wish you could've played around with it. 

I am excited to implement the new feature. In case you're still the one to check it out, I hope the app will run and I'm happy to hear your thoughts on it.
